// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThiSmartUI.Models;

#nullable disable

namespace ThiSmartUI.Migrations
{
    [DbContext(typeof(ExamSystemContext))]
    partial class ExamSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThiSmartUI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id")
                        .HasName("PK__categori__3213E83FC9886B27");

                    b.HasIndex("ParentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("ThiSmartUI.Models.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AntiCheatSettings")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("anti_cheat_settings");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<bool?>("IsRandom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_random");

                    b.Property<decimal?>("PassScore")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("pass_score");

                    b.Property<string>("SnapshotUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("snapshot_url");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK__exams__3213E83F361A29AA");

                    b.HasIndex("TeacherId");

                    b.ToTable("exams", (string)null);
                });

            modelBuilder.Entity("ThiSmartUI.Models.ExamQuestion", b =>
                {
                    b.Property<int>("ExamId")
                        .HasColumnType("int")
                        .HasColumnName("exam_id");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("question_id");

                    b.Property<int?>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.HasKey("ExamId", "QuestionId")
                        .HasName("PK__exam_que__1E605ABDADC18F90");

                    b.HasIndex("QuestionId");

                    b.ToTable("exam_questions", (string)null);
                });

            modelBuilder.Entity("ThiSmartUI.Models.ExamSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("access_code");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_time");

                    b.Property<int?>("ExamId")
                        .HasColumnType("int")
                        .HasColumnName("exam_id");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("PK__exam_ses__3213E83FD397FDEA");

                    b.HasIndex("ExamId");

                    b.HasIndex(new[] { "AccessCode" }, "UQ__exam_ses__D304327196FD30D6")
                        .IsUnique()
                        .HasFilter("[access_code] IS NOT NULL");

                    b.HasIndex(new[] { "AccessCode" }, "idx_exam_access_code");

                    b.ToTable("exam_sessions", (string)null);
                });

            modelBuilder.Entity("ThiSmartUI.Models.ProctoringLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttemptId")
                        .HasColumnType("int")
                        .HasColumnName("attempt_id");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("details");

                    b.Property<string>("EventType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("event_type");

                    b.Property<DateTime?>("LogTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("log_time")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("Id")
                        .HasName("PK__proctori__3213E83F6795B251");

                    b.HasIndex(new[] { "AttemptId" }, "idx_proctoring_attempt");

                    b.ToTable("proctoring_logs", (string)null);
                });

            modelBuilder.Entity("ThiSmartUI.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<string>("Level")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("level");

                    b.Property<string>("QuestionType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("MultipleChoice")
                        .HasColumnName("question_type");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id")
                        .HasName("PK__question__3213E83F9C6A1D79");

                    b.HasIndex("TeacherId");

                    b.HasIndex(new[] { "CategoryId" }, "idx_question_category");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("ThiSmartUI.Models.QuestionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<bool?>("IsCorrect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_correct");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("question_id");

                    b.HasKey("Id")
                        .HasName("PK__question__3213E83FCCB8D8B4");

                    b.HasIndex("QuestionId");

                    b.ToTable("question_options", (string)null);
                });

            modelBuilder.Entity("ThiSmartUI.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role_name");

                    b.HasKey("Id")
                        .HasName("PK__roles__3213E83F572C2184");

                    b.HasIndex(new[] { "RoleName" }, "UQ__roles__783254B1775C2742")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("ThiSmartUI.Models.StudentAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptId")
                        .HasColumnType("int")
                        .HasColumnName("attempt_id");

                    b.Property<string>("EssayAnswer")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("essay_answer");

                    b.Property<bool?>("IsFlagged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_flagged");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("question_id");

                    b.Property<int?>("SelectedOptionId")
                        .HasColumnType("int")
                        .HasColumnName("selected_option_id");

                    b.HasKey("Id")
                        .HasName("PK__student___3213E83FCEA8D736");

                    b.HasIndex("AttemptId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SelectedOptionId");

                    b.ToTable("student_answers", (string)null);
                });

            modelBuilder.Entity("ThiSmartUI.Models.StudentAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    b.Property<DateTime?>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("In-Progress")
                        .HasColumnName("status");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("submitted_at");

                    b.Property<decimal?>("TotalScore")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("total_score");

                    b.HasKey("Id")
                        .HasName("PK__student___3213E83F3E6CFBF9");

                    b.HasIndex("StudentId");

                    b.HasIndex(new[] { "SessionId" }, "idx_student_attempt_session");

                    b.ToTable("student_attempts", (string)null);
                });

            modelBuilder.Entity("ThiSmartUI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PK__users__3213E83FA4AE5AF3");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__users__AB6E6164CB76162D")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "UQ__users__F3DBC572CA51E503")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ThiSmartUI.Models.Category", b =>
                {
                    b.HasOne("ThiSmartUI.Models.Category", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK_categories_parent");

                    b.HasOne("ThiSmartUI.Models.User", "Teacher")
                        .WithMany("Categories")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("FK_categories_teacher");

                    b.Navigation("Parent");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ThiSmartUI.Models.Exam", b =>
                {
                    b.HasOne("ThiSmartUI.Models.User", "Teacher")
                        .WithMany("Exams")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("FK_exams_teacher");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ThiSmartUI.Models.ExamQuestion", b =>
                {
                    b.HasOne("ThiSmartUI.Models.Exam", "Exam")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_exam_questions_exam");

                    b.HasOne("ThiSmartUI.Models.Question", "Question")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_exam_questions_question");

                    b.Navigation("Exam");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ThiSmartUI.Models.ExamSession", b =>
                {
                    b.HasOne("ThiSmartUI.Models.Exam", "Exam")
                        .WithMany("ExamSessions")
                        .HasForeignKey("ExamId")
                        .HasConstraintName("FK_sessions_exam");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("ThiSmartUI.Models.ProctoringLog", b =>
                {
                    b.HasOne("ThiSmartUI.Models.StudentAttempt", "Attempt")
                        .WithMany("ProctoringLogs")
                        .HasForeignKey("AttemptId")
                        .HasConstraintName("FK_logs_attempt");

                    b.Navigation("Attempt");
                });

            modelBuilder.Entity("ThiSmartUI.Models.Question", b =>
                {
                    b.HasOne("ThiSmartUI.Models.Category", "Category")
                        .WithMany("Questions")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_questions_category");

                    b.HasOne("ThiSmartUI.Models.User", "Teacher")
                        .WithMany("Questions")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("FK_questions_teacher");

                    b.Navigation("Category");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ThiSmartUI.Models.QuestionOption", b =>
                {
                    b.HasOne("ThiSmartUI.Models.Question", "Question")
                        .WithMany("QuestionOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_options_question");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ThiSmartUI.Models.StudentAnswer", b =>
                {
                    b.HasOne("ThiSmartUI.Models.StudentAttempt", "Attempt")
                        .WithMany("StudentAnswers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_answers_attempt");

                    b.HasOne("ThiSmartUI.Models.Question", "Question")
                        .WithMany("StudentAnswers")
                        .HasForeignKey("QuestionId")
                        .HasConstraintName("FK_answers_question");

                    b.HasOne("ThiSmartUI.Models.QuestionOption", "SelectedOption")
                        .WithMany("StudentAnswers")
                        .HasForeignKey("SelectedOptionId")
                        .HasConstraintName("FK_answers_option");

                    b.Navigation("Attempt");

                    b.Navigation("Question");

                    b.Navigation("SelectedOption");
                });

            modelBuilder.Entity("ThiSmartUI.Models.StudentAttempt", b =>
                {
                    b.HasOne("ThiSmartUI.Models.ExamSession", "Session")
                        .WithMany("StudentAttempts")
                        .HasForeignKey("SessionId")
                        .HasConstraintName("FK_attempts_session");

                    b.HasOne("ThiSmartUI.Models.User", "Student")
                        .WithMany("StudentAttempts")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK_attempts_student");

                    b.Navigation("Session");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ThiSmartUI.Models.User", b =>
                {
                    b.HasOne("ThiSmartUI.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_users_roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ThiSmartUI.Models.Category", b =>
                {
                    b.Navigation("InverseParent");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("ThiSmartUI.Models.Exam", b =>
                {
                    b.Navigation("ExamQuestions");

                    b.Navigation("ExamSessions");
                });

            modelBuilder.Entity("ThiSmartUI.Models.ExamSession", b =>
                {
                    b.Navigation("StudentAttempts");
                });

            modelBuilder.Entity("ThiSmartUI.Models.Question", b =>
                {
                    b.Navigation("ExamQuestions");

                    b.Navigation("QuestionOptions");

                    b.Navigation("StudentAnswers");
                });

            modelBuilder.Entity("ThiSmartUI.Models.QuestionOption", b =>
                {
                    b.Navigation("StudentAnswers");
                });

            modelBuilder.Entity("ThiSmartUI.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ThiSmartUI.Models.StudentAttempt", b =>
                {
                    b.Navigation("ProctoringLogs");

                    b.Navigation("StudentAnswers");
                });

            modelBuilder.Entity("ThiSmartUI.Models.User", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Exams");

                    b.Navigation("Questions");

                    b.Navigation("StudentAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
